services:
  - type: web
    name: main-server
    env: node
    rootDir: Research-1
    buildCommand: npm install
    startCommand: node Server.js
    plan: free

  - type: web
    name: admin-server
    env: node
    rootDir: Research-1/Admin Data
    buildCommand: npm install
    startCommand: node Server.js
    plan: free

  - type: web
    name: author-server
    env: node
    rootDir: Research-1/Author Page
    buildCommand: npm install
    startCommand: node Server.js
    plan: free

  - type: web
    name: meeting-server
    env: node
    rootDir: Research-1/Meeting
    buildCommand: npm install
    startCommand: node Server.js
    plan: free
